'use client';

import { useState } from 'react';
import { ArrowUpRight, Check, Menu, X, ShieldCheck, SlidersHorizontal, Wallet, ChartNoAxesCombined, CircleHelp, Plus, Minus, Sparkles } from 'lucide-react';

const money = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
const tabs = ['Overview', 'Spending', 'Goals'];
const faqs = [
  ['What can I do with Fermor?', 'Understand your financial picture, explore everyday money decisions, and plan for your goals. Start with a calculator, change the numbers, and see the trade-offs for yourself.'],
  ['Do I need to connect my bank account?', 'No. The planning tool on this page works with numbers you enter yourself. It does not connect to a bank, and your calculator inputs are never sent to a server.'],
  ['Are the projected returns guaranteed?', 'No. The calculator uses a fixed assumed annual return to illustrate compound growth. Actual returns vary, and the estimate excludes taxes, fees, and inflation.'],
  ['Is this financial advice?', 'These tools are for education and exploration. Fermor is not a SEBI-registered investment adviser. For advice about your situation, speak with a qualified adviser.']
];

function GrowthChart({ compact = false }: { compact?: boolean }) {
  return <svg className={compact ? 'chart compact' : 'chart'} viewBox="0 0 480 170" role="img" aria-label="Illustrative wealth growth over time"><defs><linearGradient id={compact ? 'smallFill' : 'growthFill'} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a7ca4a" stopOpacity=".4"/><stop offset="100%" stopColor="#a7ca4a" stopOpacity="0"/></linearGradient></defs>{[30,75,120].map(y=><line key={y} x1="0" y1={y} x2="480" y2={y} stroke="#edf0e9" strokeDasharray="4 5"/>)}<path d="M0 152 C50 146 55 136 90 139 S135 112 170 119 S200 99 240 98 S280 72 320 73 S358 49 390 52 S430 20 480 12 L480 170 L0 170Z" fill={`url(#${compact ? 'smallFill' : 'growthFill'})`}/><path d="M0 152 C50 146 55 136 90 139 S135 112 170 119 S200 99 240 98 S280 72 320 73 S358 49 390 52 S430 20 480 12" fill="none" stroke="#7a9c28" strokeWidth="3"/></svg>;
}

export default function Home() {
 const [menu, setMenu] = useState(false);
 const [tab, setTab] = useState('Overview');
 const [monthly, setMonthly] = useState(5000);
 const [years, setYears] = useState(10);
 const [rate, setRate] = useState(10);
 const [faq, setFaq] = useState<number|null>(0);
 const months=years*12, r=rate/1200;
 const invested=monthly*months;
 const total=r===0 ? invested : monthly*((Math.pow(1+r,months)-1)/r)*(1+r);
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <header className="header"><div className="container nav"><a className="brand" href="#" aria-label="Fermor home"><span className="brand-symbol">f</span>fermor<span className="brand-dot">.</span></a><nav className={menu?'nav-links open':'nav-links'} aria-label="Main navigation"><a href="#why" onClick={()=>setMenu(false)}>Why Fermor</a><a href="#planner" onClick={()=>setMenu(false)}>Plan your future</a><a href="#questions" onClick={()=>setMenu(false)}>FAQs</a></nav><a className="button small nav-cta" href="#planner">Start exploring</a><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="main">
 <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="tiny-mark"/> A LITTLE CLARITY. A LOT OF POSSIBILITY.</div><h1>Less money<br/>worry.<br/><span>More life.</span></h1><p>Your money has a bigger story to tell. Understand where you stand, make confident decisions, and build a future that feels like you.</p><div className="hero-actions"><a className="button" href="#planner">Find your starting point</a><a className="text-link" href="#why">Meet Fermor <span>↗</span></a></div><div className="hero-note"><ShieldCheck size={17}/> No bank connection needed. Start with your numbers.</div></div>
 <div className="hero-visual"><div className="visual-top"><span>YOUR MONEY, IN PERSPECTIVE</span><span className="sample-badge">Interactive preview</span></div><div className="dashboard"><div className="dashboard-head"><div><span className="muted">Your financial picture</span><h2>A good place to grow.</h2></div><span className="avatar">A</span></div><div className="dashboard-tabs" role="tablist" aria-label="Financial preview">{tabs.map(t=><button key={t} id={`tab-${t}`} role="tab" aria-selected={t===tab} aria-controls="preview-panel" onClick={()=>setTab(t)}>{t}</button>)}</div><div id="preview-panel" role="tabpanel" aria-labelledby={`tab-${tab}`}>
 {tab==='Overview'?<><div className="balance"><span>Total net worth</span><strong>₹8,42,500</strong><span className="positive"><ArrowUpRight size={14}/> ₹42,500 this month</span></div><GrowthChart/><div className="chart-labels"><span>JAN</span><span>FEB</span><span>MAR</span><span>APR</span><span>MAY</span><span>JUN</span></div><div className="asset-row"><div><span className="asset-dot navy"/> Investments<strong>₹5,60,000</strong></div><div><span className="asset-dot lime"/> Savings<strong>₹2,82,500</strong></div></div></>:tab==='Spending'?<div className="spending-panel"><span className="muted">This month’s spending</span><strong>₹28,400</strong>{[['Living essentials',52,'₹14,768'],['A little enjoyment',28,'₹7,952'],['Everything else',20,'₹5,680']].map(([label,value,amount])=><div className="spend-item" key={label}><div><span>{label}</span><b>{amount}</b></div><div className="progress"><span style={{width:`${value}%`}}/></div></div>)}</div>:<div className="goals-panel"><span className="muted">Make space for what matters</span>{[['Emergency fund','₹1,50,000 of ₹2,00,000',75],['A trip to remember','₹45,000 of ₹80,000',56],['Your first home','₹3,00,000 of ₹10,00,000',30]].map(([label,amount,value])=><div className="spend-item" key={label}><div><b>{label}</b><span>{value}%</span></div><div className="progress"><span style={{width:`${value}%`}}/></div><small>{amount}</small></div>)}</div>}
 </div><div className="dashboard-bottom"><ShieldCheck size={14}/> Sample data. Your possibilities.</div></div><div className="insight-card"><span className="insight-icon"><Sparkles size={19}/></span><div><strong>Small steps. Real progress.</strong><p>Your future starts with what you do today.</p></div><Check size={17}/></div><div className="visual-caption">UNDERSTAND TODAY <span> / </span> BUILD TOMORROW</div></div>
 </section>
 <div className="principles container"><span>Good with money.<br/><strong>Better at life.</strong></span><div><Check/> Clarity before complexity</div><div><Check/> Your goals, your pace</div><div><Check/> Numbers you can understand</div></div>
 <section className="why container section" id="why"><div className="section-heading"><div><span className="eyebrow">A CLEARER WAY FORWARD</span><h2>Money makes more sense<br/>when it all comes together.</h2></div><p>From the everyday to the someday.<br/>Find the connection between your money<br/>and the life you want to live.</p></div><div className="feature-grid"><article className="feature-card"><span className="feature-icon"><Wallet/></span><span className="step">01 / UNDERSTAND</span><h3>See the whole picture.</h3><p>Bring savings, spending, and investments into perspective. Start with where you are, without the guesswork.</p><div className="mini-overview"><div><span>Money in</span><b>₹65,000</b></div><div className="mini-bars"><span/><span/><span/><span/><span/><span/></div><span className="mini-caption">More awareness. Better decisions.</span></div></article><article className="feature-card"><span className="feature-icon"><SlidersHorizontal/></span><span className="step">02 / PLAN</span><h3>Turn “what if” into a plan.</h3><p>A home, a rainy-day fund, or a little more freedom. Explore the numbers behind what matters to you.</p><div className="mini-goal"><span>Your next chapter</span><strong>A place of your own</strong><div className="progress"><span style={{width:'64%'}}/></div><div><span>One step closer</span><b>64%</b></div></div></article><article className="feature-card"><span className="feature-icon"><ChartNoAxesCombined/></span><span className="step">03 / GROW</span><h3>Build a little, consistently.</h3><p>You don’t need to know everything to begin. See how regular contributions can support your long-term goals.</p><div className="mini-growth"><span>Consistency compounds.</span><GrowthChart compact/></div></article></div></section>
 <section className="planner-section" id="planner"><div className="container planner-layout"><div className="planner-copy"><span className="eyebrow">YOUR SOMEDAY STARTS TODAY</span><h2>What could your<br/><span>next decade</span><br/>look like?</h2><p>Big plans can begin with a small monthly habit. Adjust the numbers and see one possible path for your savings.</p><div className="planner-privacy"><ShieldCheck size={20}/><span>Just you and the numbers.<br/><b>Your inputs stay in your browser.</b></span></div></div><div className="calculator"><div className="calc-top"><h3>Your growth planner</h3><span><SlidersHorizontal size={17}/> SIP calculator</span></div><div className="controls"><label htmlFor="monthly"><span>Monthly investment</span><output>{money(monthly)}</output></label><input id="monthly" type="range" min="500" max="50000" step="500" value={monthly} onChange={e=>setMonthly(Number(e.target.value))}/><div className="range-labels"><span>₹500</span><span>₹50,000</span></div><label htmlFor="years"><span>Time to grow</span><output>{years} years</output></label><input id="years" type="range" min="1" max="30" value={years} onChange={e=>setYears(Number(e.target.value))}/><div className="range-labels"><span>1 year</span><span>30 years</span></div><label htmlFor="rate"><span>Expected annual return <CircleHelp size={14}/></span><output>{rate}%</output></label><input id="rate" type="range" min="0" max="20" step=".5" value={rate} onChange={e=>setRate(Number(e.target.value))}/></div><div className="calc-result" aria-live="polite"><span>In {years} years, you could have</span><strong>{money(total)}</strong><div className="result-bar"><span style={{width:`${invested/total*100}%`}}/></div><div className="result-breakdown"><span><i className="navy"/> You invest <b>{money(invested)}</b></span><span><i className="lime"/> Estimated growth <b>{money(total-invested)}</b></span></div></div><p className="calc-disclaimer">Illustrative estimate with monthly contributions at the beginning of each month. Returns are not guaranteed. Excludes taxes, fees, and inflation.</p></div></div></section>
 <section className="questions container section" id="questions"><div><span className="eyebrow">LET’S CLEAR THINGS UP</span><h2>A few good<br/>questions.</h2><p>Simple answers.<br/>Because money is complicated enough.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={faq===i?'faq active':'faq'} key={q}><h3><button aria-expanded={faq===i} aria-controls={`faq-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={18}/>:<Plus size={18}/>}</button></h3><div id={`faq-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></section>
 <section className="final-cta container"><span className="eyebrow">A BETTER RELATIONSHIP WITH MONEY</span><h2>Your future.<br/>A little clearer.</h2><p>You don’t need all the answers. Just a place to start.</p><a className="button light" href="#planner">Take the first step</a><span className="cta-decoration" aria-hidden="true">f.</span></section>
 </main><footer className="container"><div className="footer-top"><a className="brand" href="#"><span className="brand-symbol">f</span>fermor<span className="brand-dot">.</span></a><p>Understand. Act. Grow.</p><a href="#main">Back to top ↑</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Fermor. Homepage concept.</span><span>Made for clearer money decisions.</span></div></footer>
 </>;
}
